#!/usr/bin/expect -f

set timeout 60
set host "185.213.175.124"
set port "22"
set user "root"
set password "Cej1SRY4wgl$"

log_user 1

spawn ssh -p $port -o StrictHostKeyChecking=no $user@$host

expect {
    "password:" {
        send "$password\r"
        exp_continue
    }
    "#" {
        send "echo '=== Getting all servers ==='\r"
        expect "#"
        send "sqlite3 /opt/dstatus/data/db.db \"SELECT sid, name, display_index FROM servers WHERE deleted_at IS NULL ORDER BY display_index;\"\r"
        expect "#"
        send "exit\r"
    }
}

expect eof
