#!/bin/bash

# 手动部署到测试环境
SERVER="91.233.10.38"
USER="root"
PASSWORD="8ldnSIgH86xCRQczqQYi"

echo "=== 上传文件到服务器 ==="

# 上传文件
sshpass -p "$PASSWORD" scp -P 22 -o StrictHostKeyChecking=no ./bin/panel-linux $USER@$SERVER:/opt/realm-flow/panel
sshpass -p "$PASSWORD" scp -P 22 -o StrictHostKeyChecking=no -r ./react-frontend/dist $USER@$SERVER:/opt/realm-flow/

echo "文件上传完成"
echo ""
echo "请手动 SSH 到服务器执行以下命令："
echo ""
echo "ssh root@91.233.10.38"
echo ""
echo "cd /opt/realm-flow"
echo "chmod +x panel"
echo "mkdir -p logs"
echo ""
echo "# 创建 systemd 服务"
echo 'cat > /etc/systemd/system/realmflow-panel.service << EOF'
echo "[Unit]"
echo "Description=RealmFlow Panel"
echo "After=network.target"
echo ""
echo "[Service]"
echo "Type=simple"
echo "User=root"
echo "WorkingDirectory=/opt/realm-flow"
echo "ExecStart=/opt/realm-flow/panel"
echo "Environment=DATABASE_URL=postgres://realmflow:realmflow@localhost:5432/realmflow?sslmode=disable"
echo "Environment=JWT_SECRET=your-secret-key-change-in-production"
echo "Environment=PORT=6365"
echo "Restart=always"
echo "RestartSec=10"
echo ""
echo "[Install]"
echo "WantedBy=multi-user.target"
echo "EOF"
echo ""
echo "# 启动面板"
echo "systemctl daemon-reload"
echo "systemctl enable realmflow-panel"
echo "systemctl start realmflow-panel"
echo ""
echo "# 安装并配置 nginx"
echo "apt-get install -y nginx"
echo 'cat > /etc/nginx/sites-available/realmflow << EOF'
echo "server {"
echo "    listen 80;"
echo "    server_name _;"
echo "    root /opt/realm-flow/dist;"
echo "    index index.html;"
echo ""
echo "    location / {"
echo "        try_files \$uri \$uri/ /index.html;"
echo "    }"
echo ""
echo "    location /api/ {"
echo "        proxy_pass http://localhost:6365/api/;"
echo "        proxy_set_header Host \$host;"
echo "        proxy_set_header X-Real-IP \$remote_addr;"
echo "        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
echo "    }"
echo "}"
echo "EOF"
echo ""
echo "ln -sf /etc/nginx/sites-available/realmflow /etc/nginx/sites-enabled/"
echo "rm -f /etc/nginx/sites-enabled/default"
echo "systemctl restart nginx"
echo ""
echo "# 安装 PostgreSQL"
echo "apt-get install -y postgresql"
echo "su - postgres -c \"psql -c \\\"CREATE USER realmflow WITH PASSWORD 'realmflow';\\\"\""
echo "su - postgres -c \"psql -c \\\"CREATE DATABASE realmflow OWNER realmflow;\\\"\""
echo ""
echo "echo '部署完成！访问 http://91.233.10.38'"
